using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Spheris.Billing.Core.Domain
{
    public class WorkUnit
    {
        public long? WorkUnitID;
        public string ExtSys;
        public string ExtWorkUnitKey;
        public string ExtClientKey;
        public string ExtWorkType;
        public string WorkUnitStatus = "NT";
        public int? InvoiceID;
        public DateTime? ReverseRequestedOn;
        public string ReverseRequestedBy;
        public string ReversalReason;
        public int? ReversedOnInvoiceID;
        public string JobNbr;
        public string Urgency;
        public string AttendingID;
        public string AttendingName;
        public string AttendingSpecialty;
        public string MTID;
        public string MTName;
        public string DictatorID;
        public string DictatorName;
        public string DictatorSpecialty;
        public string DictatorCostCode;
        public DateTime? DictatedOn;
        public Single? DictationSeconds;
        public DateTime? TatBeginsOn;
        public DateTime? TatEndsOn;
        public string PatientID;
        public int? CharsTotal;
        public int? CharsNoSpaces;
        public int? CharsMT;
        public Single? QtyBillable;
        public Single? LinesGross;
        public Single? Words;
        public Single? Paragraphs;
        public Single? Pages;
        public int? RevisionNbr;
        public DateTime? HostInterfaceAnchor;
        public int? Status;
        public DateTime? StatusChangedOn;
        public string DictationID;
        public string Department;
        public string CustomerAcctNbr;
        public string InvoiceGrpOverrideKey;
        public DateTime? InsertedOn;
        public Single? RawCost;
        public Single? TatReductionCalculated;
        public Single? TatReductionCharged;
        public Single? BaseRate;
        public Single? TatRate;
        public Single? ClassPctOverTat;
        public DateTime? ChangedOn;
        public string PatientFirst;
        public string PatientLast;
        public DateTime? BillableOn;
        public int? ReportID;
        public string FirstMTID;
        public int? ParentWorkUnitID;
        public string EntryLocation;
        public Single? RateApplied;
        public Single? TatThresholdApplied;
        public Single? DictatorSRScore;
        public Single? DocumentSRScore;
        public string ServiceType;
        public string ServiceProvider;
        public string Custom1;
        public string Custom2;
        public string Custom3;
        public int? VirtualLocationID;
        public string LocationName;
        public string ClientDicatatorID;
        public int? ClientWorkTypeID;
        public string ServiceProviderName;
        public int? DictatingPhysicianID;
        public string PatientCostCenter;
        public string PatientLocation;
        public string PatientRoom;
        public string PrintLocation;
        public string ActivityType;
        public string ClinicCode;
        public Single? DepCount;
    }
}
